use_frameworks!
inhibit_all_warnings!
platform :ios, '15.0'

# Please use 'pod install --repo-update' to ensure you have the latest versions of our SDKs.

target 'AppLovin MAX Demo App - ObjC' do
  pod 'AppLovinSDK', '13.3.1'
  pod 'Adjust'
  pod 'HyBid',  :podspec => './HyBid.podspec'
  pod 'AppLovinMediationVerveAdapter', :podspec => './AppLovinMediationVerveAdapter.podspec'
end
